import { Document } from '@contentful/rich-text-types';
// Generated by https://quicktype.io

export interface BlogList {
  sys: DSys;
  total: number;
  skip: number;
  limit: number;
  items: Item[];
  includes: Includes;
}

export interface Includes {
  Asset: Asset[];
}

export interface Asset {
  metadata: Metadata;
  sys: AssetSys;
  fields: AssetFields;
}

export interface AssetFields {
  title: string;
  description: string;
  file: File;
}

export interface File {
  url: string;
  details: Details;
  fileName: string;
  contentType: string;
}

export interface Details {
  size: number;
  image: Image;
}

export interface Image {
  width: number;
  height: number;
}

export interface Metadata {
  tags: any[];
}

export interface AssetSys {
  space: ContentType;
  id: string;
  type: string;
  createdAt: string;
  updatedAt: string;
  environment: ContentType;
  revision: number;
  locale: string;
  contentType?: ContentType;
}

export interface ContentType {
  sys: ContentTypeSys;
}

export interface ContentTypeSys {
  id: string;
  type: string;
  linkType: string;
}

export interface Item {
  metadata: Metadata;
  sys: AssetSys;
  fields: ItemFields;
}

export interface ItemFields {
  title: string;
  description: string;
  browserDescription: string;
  browserTitle: string;
  text: Document;
  image: Asset;
  altImage: string;
  slug: string;
}


export interface TextContent {
  data: any;
  content: ContentContent[];
  nodeType: string;
}

export interface ContentContent {
  data: any;
  marks: any[];
  value: string;
  nodeType: string;
}

export interface DSys {
  type: string;
}
