import './global.css';
import { StyleConfig } from '@org/ui';

export const metadata = {
  title: 'Welcome to org',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
  
}: {
  children: React.ReactNode;
  
}) {

  return children;
}
